print("""
      It is not the critic who counts; 
      not the man who points out how the strong man stumbles,
      or where the doer of deeds could have done them better.
      The credit belongs to the man who is actually in the arena, 
      whose face is marred by dust and sweat and blood;
      who strives valiantly; 
      who errs, who comes short again and again,
      because there is no effort without error and shortcoming;
      but who does actually strive to do the deeds;
      who knows great enthusiasms, the great devotions;
      who spends himself in a worthy cause;
      who at the best knows in the end the triumph of high achievement,
      and who at the worst,
      if he fails,
      at least fails while daring greatly,
      so that his place shall never be with those cold and timid souls 
      
      who neither know victory nor defeat.
      """)
      
text = ("""
      It is not the critic who counts; 
      not the man who points out how the strong man stumbles,
      or where the doer of deeds could have done them better.
      The credit belongs to the man who is actually in the arena, 
      whose face is marred by dust and sweat and blood;
      who strives valiantly; 
      who errs, who comes short again and again,
      because there is no effort without error and shortcoming;
      but who does actually strive to do the deeds;
      who knows great enthusiasms, the great devotions;
      who spends himself in a worthy cause;
      who at the best knows in the end the triumph of high achievement,
      and who at the worst,
      if he fails,
      at least fails while daring greatly,
      so that his place shall never be with those cold and timid souls 
      
      who neither know victory nor defeat.
      """)
#Above is an excerpt of the Man in the Arena speech by Teddy Roosevelt. 
#I made it a variable and we are going to do some analysis.
# This is going to tell us how many characters are wilthin that string / tuplo.       
print(len(text))

#By adding .split we have added functionality to the variable. We are telling the code to 
#extrapolate every instance where there is a space separating two words and calling it a unique item.
print(text.split())

#I wanted to find a way to make this a list so that I could pull characters... This didn't work.
mylist_text = (text.split)

#The split functionality gives you a temporary function but it's something you need to know how to call. 
#You don't need to assign it a variable because you can basically always call it. So I guess that's why
#you can't assign it a variable? 
#This command let's you determine how many items are in the temporary list generated by split. 
print(len(text.split()))

#I have created a blank dictionary called word count. 
word_count ={}

#All strings are changed to lower case to remove unncessary dupes. 


for word in text.lower().split():
    if word in word_count:
        word_count[word] += 1  #This is the same as adding word_count[word] = word_count[word] +1
    else:
        word_count[word] = 1
    
print(word_count)


